/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Booking_meeting: typeof import('./src/components/booking/booking_meeting.vue')['default']
    Booking_study: typeof import('./src/components/booking/booking_study.vue')['default']
    Detail_room: typeof import('./src/components/home/detail_room.vue')['default']
    Footer_page: typeof import('./src/components/footer/footer_page.vue')['default']
    Form_equipment: typeof import('./src/components/form/form_equipment.vue')['default']
    Form_meeting: typeof import('./src/components/form/form_meeting.vue')['default']
    Form_restaurant: typeof import('./src/components/form/form_restaurant.vue')['default']
    Form_study: typeof import('./src/components/form/form_study.vue')['default']
    Header_page: typeof import('./src/components/header/header_page.vue')['default']
    Home_page: typeof import('./src/components/home/home_page.vue')['default']
    Login_page: typeof import('./src/components/home/login_page.vue')['default']
    Manage_room: typeof import('./src/components/status/manage_room.vue')['default']
    Manage_status: typeof import('./src/components/status/manage_status.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Status_page: typeof import('./src/components/status/status_page.vue')['default']
    Table_entertain: typeof import('./src/components/table/table_entertain.vue')['default']
    Table_meeting: typeof import('./src/components/table/table_meeting.vue')['default']
    Table_study: typeof import('./src/components/table/table_study.vue')['default']
  }
}
