/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/booking/booking_meeting': RouteRecordInfo<'/booking/booking_meeting', '/booking/booking_meeting', Record<never, never>, Record<never, never>>,
    '/booking/booking_study': RouteRecordInfo<'/booking/booking_study', '/booking/booking_study', Record<never, never>, Record<never, never>>,
    '/booking_meeting': RouteRecordInfo<'/booking_meeting', '/booking_meeting', Record<never, never>, Record<never, never>>,
    '/booking_study': RouteRecordInfo<'/booking_study', '/booking_study', Record<never, never>, Record<never, never>>,
    '/detail_room': RouteRecordInfo<'/detail_room', '/detail_room', Record<never, never>, Record<never, never>>,
    '/footer/footer_page': RouteRecordInfo<'/footer/footer_page', '/footer/footer_page', Record<never, never>, Record<never, never>>,
    '/form/form_equipment': RouteRecordInfo<'/form/form_equipment', '/form/form_equipment', Record<never, never>, Record<never, never>>,
    '/form/form_meeting': RouteRecordInfo<'/form/form_meeting', '/form/form_meeting', Record<never, never>, Record<never, never>>,
    '/form/form_restaurant': RouteRecordInfo<'/form/form_restaurant', '/form/form_restaurant', Record<never, never>, Record<never, never>>,
    '/form/form_study': RouteRecordInfo<'/form/form_study', '/form/form_study', Record<never, never>, Record<never, never>>,
    '/form_equipment': RouteRecordInfo<'/form_equipment', '/form_equipment', Record<never, never>, Record<never, never>>,
    '/form_meeting': RouteRecordInfo<'/form_meeting', '/form_meeting', Record<never, never>, Record<never, never>>,
    '/form_restaurant': RouteRecordInfo<'/form_restaurant', '/form_restaurant', Record<never, never>, Record<never, never>>,
    '/form_study': RouteRecordInfo<'/form_study', '/form_study', Record<never, never>, Record<never, never>>,
    '/header/header_page': RouteRecordInfo<'/header/header_page', '/header/header_page', Record<never, never>, Record<never, never>>,
    '/home/detail_room': RouteRecordInfo<'/home/detail_room', '/home/detail_room', Record<never, never>, Record<never, never>>,
    '/home/home_page': RouteRecordInfo<'/home/home_page', '/home/home_page', Record<never, never>, Record<never, never>>,
    '/home/login_page': RouteRecordInfo<'/home/login_page', '/home/login_page', Record<never, never>, Record<never, never>>,
    '/home_page': RouteRecordInfo<'/home_page', '/home_page', Record<never, never>, Record<never, never>>,
    '/login_page': RouteRecordInfo<'/login_page', '/login_page', Record<never, never>, Record<never, never>>,
    '/manage_room': RouteRecordInfo<'/manage_room', '/manage_room', Record<never, never>, Record<never, never>>,
    '/manage_status': RouteRecordInfo<'/manage_status', '/manage_status', Record<never, never>, Record<never, never>>,
    '/status/manage_room': RouteRecordInfo<'/status/manage_room', '/status/manage_room', Record<never, never>, Record<never, never>>,
    '/status/manage_status': RouteRecordInfo<'/status/manage_status', '/status/manage_status', Record<never, never>, Record<never, never>>,
    '/status/status_page': RouteRecordInfo<'/status/status_page', '/status/status_page', Record<never, never>, Record<never, never>>,
    '/status_page': RouteRecordInfo<'/status_page', '/status_page', Record<never, never>, Record<never, never>>,
    '/table/table_entertain': RouteRecordInfo<'/table/table_entertain', '/table/table_entertain', Record<never, never>, Record<never, never>>,
    '/table/table_meeting': RouteRecordInfo<'/table/table_meeting', '/table/table_meeting', Record<never, never>, Record<never, never>>,
    '/table/table_study': RouteRecordInfo<'/table/table_study', '/table/table_study', Record<never, never>, Record<never, never>>,
    '/table_entertain': RouteRecordInfo<'/table_entertain', '/table_entertain', Record<never, never>, Record<never, never>>,
    '/table_meeting': RouteRecordInfo<'/table_meeting', '/table_meeting', Record<never, never>, Record<never, never>>,
    '/table_study': RouteRecordInfo<'/table_study', '/table_study', Record<never, never>, Record<never, never>>,
  }
}
