/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/header/header_page': RouteRecordInfo<'/header/header_page', '/header/header_page', Record<never, never>, Record<never, never>>,
    '/home/home_page': RouteRecordInfo<'/home/home_page', '/home/home_page', Record<never, never>, Record<never, never>>,
    '/home/login_page': RouteRecordInfo<'/home/login_page', '/home/login_page', Record<never, never>, Record<never, never>>,
    '/home_page': RouteRecordInfo<'/home_page', '/home_page', Record<never, never>, Record<never, never>>,
    '/login_page': RouteRecordInfo<'/login_page', '/login_page', Record<never, never>, Record<never, never>>,
    '/table/table_entertain': RouteRecordInfo<'/table/table_entertain', '/table/table_entertain', Record<never, never>, Record<never, never>>,
    '/table/table_meeting': RouteRecordInfo<'/table/table_meeting', '/table/table_meeting', Record<never, never>, Record<never, never>>,
    '/table/table_study': RouteRecordInfo<'/table/table_study', '/table/table_study', Record<never, never>, Record<never, never>>,
    '/table_entertain': RouteRecordInfo<'/table_entertain', '/table_entertain', Record<never, never>, Record<never, never>>,
    '/table_meeting': RouteRecordInfo<'/table_meeting', '/table_meeting', Record<never, never>, Record<never, never>>,
    '/table_study': RouteRecordInfo<'/table_study', '/table_study', Record<never, never>, Record<never, never>>,
  }
}
